# Generated by Django 4.2.13 on 2024-07-09 09:35

from django.db import migrations, models
import zoneinfo

TIMEZONES_CHOICES = [(tz, tz) for tz in zoneinfo.available_timezones()]


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="timezone",
            field=models.CharField(
                choices=TIMEZONES_CHOICES, default="Africa/Johannesburg", max_length=50
            ),
        ),
    ]
