# Generated by Django 4.2.13 on 2024-07-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='website_url',
            field=models.CharField(default='', help_text='URL of your website.', max_length=255),
        ),
        migrations.AlterField(
            model_name='config',
            name='buffer_time',
            field=models.FloatField(default='15', help_text="Time between now and the first available slot for the current day (doesn't affect tomorrow).", null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='end_time',
            field=models.TimeField(default='17:00', help_text='Time when we stop working.', null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='slot_duration',
            field=models.PositiveIntegerField(default='30', help_text='Minimum time for an appointment in minutes, recommended 30.', null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='start_time',
            field=models.TimeField(default='08:00', help_text='Time when we start working.', null=True),
        ),
    ]
