# Generated by Django 4.2.13 on 2024-07-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_bookings_create_datetime_bookings_update_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
